openapi: 3.0.3
info:
  title: Dataverse Access Workflows API
  description: Open source research data repository software.
  version: v6.8.1-SP
servers:
- url: https://borealisdata.ca/api
  description: Borealis (Canadian Dataverse Repository) hosting the Queen University Dataverse
tags:
- name: Workflows
paths:
  /workflows/{invocationId}:
    post:
      operationId: Workflows_resumeWorkflow
      parameters:
      - name: invocationId
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: OK
      tags:
      - Workflows
